ALTER SEQUENCE curso_seq RESTART WITH 1 INCREMENT BY 1;

INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º DAM', 'Miguel Campos');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º DAM', 'Luis Miguel López');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º AyF', 'Juan Jiménez');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º AyF', 'Paqui García');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º FPB', 'Raúl Galán');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º FPB', 'Fernando Organvídez');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º Inst. Telecom.', 'Cecilio Delgado');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º Inst. Telec.', 'Jesús Casanova');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º Gestión Adm.', 'Alicia Ramírez');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º Gestión Adm.', 'Irene Prieto');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º Act. Comerciales', 'Mónica Sánchez');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º Act. Comerciales', 'Juan Gutiérrez');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '1º Inst. Elect.', 'Antonio Torres');
INSERT INTO CURSO (ID, NOMBRE, TUTOR) VALUES (NEXTVAL('curso_seq'), '2º Inst. Elect.', 'Rafael Villar');

insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ignacio', 'Morales', 'Dominguez', 'ignacio.morales.dominguez@email.com', 1, '1992-01-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Susana', 'Alvarez', 'Roman', 'susana.alvarez.roman@email.com', 11, '1998-02-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Hugo', 'Rodriguez', 'Mora', 'hugo.rodriguez.mora@email.com', 12, '1998-09-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Martin', 'Cortes', 'Garcia', 'martin.cortes.garcia@email.com', 13, '1990-01-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ricardo', 'Fuentes', 'Mendez', 'ricardo.fuentes.mendez@email.com', 11, '1993-10-18');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria mercedes', 'Gutierrez', 'Montero', 'mariamercedes.gutierrez.montero@email.com', 11, '1998-10-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosario', 'Gonzalez', 'Lopez', 'mariarosario.gonzalez.lopez@email.com', 6, '1994-04-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria mar', 'Romero', 'Alonso', 'mariamar.romero.alonso@email.com', 10, '1991-01-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mercedes', 'Lorenzo', 'Lopez', 'mercedes.lorenzo.lopez@email.com', 11, '1997-10-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angela', 'Alvarez', 'Calvo', 'angela.alvarez.calvo@email.com', 3, '1996-07-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria', 'Rojas', 'Gallego', 'maria.rojas.gallego@email.com', 2, '1992-03-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Domingo', 'Hernandez', 'Mora', 'domingo.hernandez.mora@email.com', 3, '1998-02-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Claudia', 'Carmona', 'Soler', 'claudia.carmona.soler@email.com', 13, '1991-10-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Noelia', 'Santiago', 'Ruiz', 'noelia.santiago.ruiz@email.com', 13, '2000-11-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Pilar', 'Molina', 'Aguilar', 'pilar.molina.aguilar@email.com', 7, '1993-04-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luisa', 'Soler', 'Romero', 'luisa.soler.romero@email.com', 13, '1995-09-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joan', 'Montero', 'Vargas', 'joan.montero.vargas@email.com', 5, '1997-09-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mercedes', 'Ortiz', 'Vargas', 'mercedes.ortiz.vargas@email.com', 12, '1993-09-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Dolores', 'Martinez', 'Hernandez', 'dolores.martinez.hernandez@email.com', 13, '1999-12-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andres', 'Alvarez', 'Suarez', 'andres.alvarez.suarez@email.com', 14, '2000-07-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose', 'Diez', 'Leon', 'jose.diez.leon@email.com', 9, '1999-01-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Carmen', 'Bravo', 'Lozano', 'carmen.bravo.lozano@email.com', 14, '1995-09-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julian', 'Suarez', 'Prieto', 'julian.suarez.prieto@email.com', 10, '1997-06-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sergio', 'Lozano', 'Iglesias', 'sergio.lozano.iglesias@email.com', 8, '1998-12-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mohamed', 'Sanchez', 'Velasco', 'mohamed.sanchez.velasco@email.com', 7, '1990-09-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Josep', 'Cortes', 'Mora', 'josep.cortes.mora@email.com', 13, '1992-07-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rosario', 'Vidal', 'Hidalgo', 'rosario.vidal.hidalgo@email.com', 4, '1992-03-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Silvia', 'Mendez', 'Cruz', 'silvia.mendez.cruz@email.com', 5, '1991-05-24');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria isabel', 'Ruiz', 'Nieto', 'mariaisabel.ruiz.nieto@email.com', 14, '1996-06-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Daniel', 'Nieto', 'Fernandez', 'daniel.nieto.fernandez@email.com', 7, '1994-07-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ignacio', 'Montero', 'Herrera', 'ignacio.montero.herrera@email.com', 14, '1995-01-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lorena', 'Montero', 'Campos', 'lorena.montero.campos@email.com', 12, '1994-07-30');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alex', 'Rubio', 'Sanz', 'alex.rubio.sanz@email.com', 2, '1996-08-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Miguel angel', 'Gomez', 'Calvo', 'miguelangel.gomez.calvo@email.com', 13, '2000-12-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Olga', 'Serrano', 'PeÑa', 'olga.serrano.peÑa@email.com', 10, '1998-02-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jesus', 'Montero', 'Cruz', 'jesus.montero.cruz@email.com', 2, '1996-07-31');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Amparo', 'Fernandez', 'Dominguez', 'amparo.fernandez.dominguez@email.com', 5, '1993-03-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Josefa', 'Carrasco', 'Delgado', 'josefa.carrasco.delgado@email.com', 2, '1999-03-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Victor', 'Cabrera', 'Marin', 'victor.cabrera.marin@email.com', 14, '1990-03-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Enrique', 'Gil', 'Delgado', 'enrique.gil.delgado@email.com', 12, '1992-07-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alejandra', 'Parra', 'Sanchez', 'alejandra.parra.sanchez@email.com', 2, '1993-04-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ismael', 'Santos', 'IbaÑez', 'ismael.santos.ibaÑez@email.com', 7, '2000-12-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ruben', 'Vidal', 'Gimenez', 'ruben.vidal.gimenez@email.com', 13, '1994-08-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Eduardo', 'Campos', 'Ramirez', 'eduardo.campos.ramirez@email.com', 7, '1994-03-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Emilia', 'Parra', 'Soto', 'emilia.parra.soto@email.com', 6, '1999-03-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jorge', 'Moya', 'Santiago', 'jorge.moya.santiago@email.com', 5, '1997-06-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Manuela', 'Carrasco', 'Serrano', 'manuela.carrasco.serrano@email.com', 1, '1991-04-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Victor manuel', 'Rojas', 'Guerrero', 'victormanuel.rojas.guerrero@email.com', 10, '1992-07-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ana isabel', 'Garrido', 'Medina', 'anaisabel.garrido.medina@email.com', 9, '2000-08-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Claudia', 'Campos', 'Arias', 'claudia.campos.arias@email.com', 8, '1993-05-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Margarita', 'Mendez', 'Rodriguez', 'margarita.mendez.rodriguez@email.com', 3, '1990-06-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julia', 'Perez', 'Campos', 'julia.perez.campos@email.com', 5, '1993-03-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joaquin', 'Diaz', 'Mora', 'joaquin.diaz.mora@email.com', 1, '1998-12-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ruben', 'Alvarez', 'Caballero', 'ruben.alvarez.caballero@email.com', 10, '1995-11-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Cesar', 'Montero', 'Arias', 'cesar.montero.arias@email.com', 7, '1994-07-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosa', 'Martin', 'Herrero', 'mariarosa.martin.herrero@email.com', 11, '1997-09-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joan', 'Duran', 'Gimenez', 'joan.duran.gimenez@email.com', 11, '1991-04-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Carolina', 'Gil', 'Romero', 'carolina.gil.romero@email.com', 13, '1994-04-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan luis', 'Parra', 'Ramirez', 'juanluis.parra.ramirez@email.com', 10, '1991-07-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luisa', 'Cruz', 'Pastor', 'luisa.cruz.pastor@email.com', 11, '1999-07-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rosa', 'Herrero', 'Hidalgo', 'rosa.herrero.hidalgo@email.com', 8, '1993-05-31');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julian', 'Cruz', 'Iglesias', 'julian.cruz.iglesias@email.com', 12, '1990-03-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Elena', 'Garcia', 'Soler', 'elena.garcia.soler@email.com', 13, '1992-10-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Encarnacion', 'Ortega', 'Sanz', 'encarnacion.ortega.sanz@email.com', 8, '1995-08-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Cristina', 'Caballero', 'Mendez', 'cristina.caballero.mendez@email.com', 14, '1992-11-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria jose', 'Herrero', 'Vidal', 'mariajose.herrero.vidal@email.com', 8, '2000-06-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Paula', 'Gonzalez', 'Gil', 'paula.gonzalez.gil@email.com', 11, '1991-08-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Marc', 'Saez', 'Calvo', 'marc.saez.calvo@email.com', 3, '1990-02-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jesus', 'Gallego', 'Martinez', 'jesus.gallego.martinez@email.com', 10, '1994-10-20');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alicia', 'Blanco', 'Iglesias', 'alicia.blanco.iglesias@email.com', 10, '1997-10-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rosa maria', 'Duran', 'Suarez', 'rosamaria.duran.suarez@email.com', 2, '1997-07-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Manuela', 'Delgado', 'Torres', 'manuela.delgado.torres@email.com', 4, '1996-11-02');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joan', 'Rubio', 'NuÑez', 'joan.rubio.nuÑez@email.com', 13, '1992-07-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Emilia', 'Suarez', 'Soler', 'emilia.suarez.soler@email.com', 13, '1991-04-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lorena', 'Moreno', 'Nieto', 'lorena.moreno.nieto@email.com', 1, '1995-01-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Diego', 'NuÑez', 'Perez', 'diego.nuÑez.perez@email.com', 10, '1991-02-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andres', 'Gimenez', 'Vidal', 'andres.gimenez.vidal@email.com', 13, '1997-01-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Monica', 'Crespo', 'Navarro', 'monica.crespo.navarro@email.com', 8, '1998-07-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luis miguel', 'Moreno', 'PeÑa', 'luismiguel.moreno.peÑa@email.com', 6, '2000-02-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rosa', 'Diez', 'Ramirez', 'rosa.diez.ramirez@email.com', 4, '1999-02-24');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'David', 'Prieto', 'Ruiz', 'david.prieto.ruiz@email.com', 9, '2000-11-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Tomas', 'PeÑa', 'Gallego', 'tomas.peÑa.gallego@email.com', 6, '1994-08-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ignacio', 'Serrano', 'Cortes', 'ignacio.serrano.cortes@email.com', 13, '1996-12-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Carla', 'Montero', 'Ferrer', 'carla.montero.ferrer@email.com', 10, '1996-06-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sandra', 'Diaz', 'Gallardo', 'sandra.diaz.gallardo@email.com', 1, '1992-07-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Celia', 'Vicente', 'MuÑoz', 'celia.vicente.muÑoz@email.com', 3, '1999-05-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Amparo', 'Hernandez', 'Herrera', 'amparo.hernandez.herrera@email.com', 4, '1992-08-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Santiago', 'NuÑez', 'Calvo', 'santiago.nuÑez.calvo@email.com', 6, '1995-04-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Roberto', 'MuÑoz', 'Carmona', 'roberto.muÑoz.carmona@email.com', 10, '1992-03-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mariano', 'Guerrero', 'Navarro', 'mariano.guerrero.navarro@email.com', 12, '1997-09-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Dolores', 'Navarro', 'Mendez', 'dolores.navarro.mendez@email.com', 14, '1992-01-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria josefa', 'Navarro', 'Gonzalez', 'mariajosefa.navarro.gonzalez@email.com', 9, '1999-05-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Felix', 'Santana', 'MuÑoz', 'felix.santana.muÑoz@email.com', 13, '1994-10-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Felix', 'Ferrer', 'Torres', 'felix.ferrer.torres@email.com', 1, '1994-10-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Marina', 'Molina', 'Carmona', 'marina.molina.carmona@email.com', 11, '1999-09-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ignacio', 'Hernandez', 'Pastor', 'ignacio.hernandez.pastor@email.com', 12, '2000-11-18');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria josefa', 'Rubio', 'Santana', 'mariajosefa.rubio.santana@email.com', 13, '1993-02-02');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Iker', 'Gutierrez', 'Marquez', 'iker.gutierrez.marquez@email.com', 9, '1992-08-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosario', 'Gil', 'Ortega', 'mariarosario.gil.ortega@email.com', 3, '1991-04-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Adrian', 'Mora', 'Santos', 'adrian.mora.santos@email.com', 13, '1995-11-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose miguel', 'Romero', 'Moya', 'josemiguel.romero.moya@email.com', 5, '1998-05-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Concepcion', 'Suarez', 'Pascual', 'concepcion.suarez.pascual@email.com', 11, '1995-02-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria victoria', 'Vidal', 'Ramos', 'mariavictoria.vidal.ramos@email.com', 13, '1990-01-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Yolanda', 'Campos', 'Delgado', 'yolanda.campos.delgado@email.com', 10, '1990-06-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jesus', 'Castillo', 'Guerrero', 'jesus.castillo.guerrero@email.com', 2, '1991-10-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan carlos', 'Pascual', 'Marquez', 'juancarlos.pascual.marquez@email.com', 10, '1992-01-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lucia', 'Pastor', 'Jimenez', 'lucia.pastor.jimenez@email.com', 5, '1990-08-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alejandra', 'Mendez', 'Calvo', 'alejandra.mendez.calvo@email.com', 4, '1994-01-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Consuelo', 'Perez', 'Roman', 'consuelo.perez.roman@email.com', 14, '1991-09-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rocio', 'PeÑa', 'Nieto', 'rocio.peÑa.nieto@email.com', 9, '1999-12-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Antonio', 'IbaÑez', 'Vicente', 'antonio.ibaÑez.vicente@email.com', 13, '1999-08-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan antonio', 'Cabrera', 'Lorenzo', 'juanantonio.cabrera.lorenzo@email.com', 6, '1996-05-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Beatriz', 'Vargas', 'Gutierrez', 'beatriz.vargas.gutierrez@email.com', 1, '2000-01-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alvaro', 'Mendez', 'Blanco', 'alvaro.mendez.blanco@email.com', 8, '1990-09-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Nicolas', 'Cortes', 'Hernandez', 'nicolas.cortes.hernandez@email.com', 14, '1998-06-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rodrigo', 'Gomez', 'Moya', 'rodrigo.gomez.moya@email.com', 3, '1992-12-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Guillermo', 'Roman', 'Ortega', 'guillermo.roman.ortega@email.com', 8, '2000-03-31');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julia', 'Alonso', 'Vidal', 'julia.alonso.vidal@email.com', 10, '1997-04-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Encarnacion', 'Fuentes', 'Navarro', 'encarnacion.fuentes.navarro@email.com', 2, '1992-11-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alejandro', 'Aguilar', 'Velasco', 'alejandro.aguilar.velasco@email.com', 6, '2000-01-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Gloria', 'Vega', 'Castillo', 'gloria.vega.castillo@email.com', 9, '1993-01-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Victoria', 'Aguilar', 'Ruiz', 'victoria.aguilar.ruiz@email.com', 8, '1994-11-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joaquin', 'Molina', 'Arias', 'joaquin.molina.arias@email.com', 6, '1997-07-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jaime', 'Gimenez', 'Santana', 'jaime.gimenez.santana@email.com', 8, '1996-08-30');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria mar', 'Carmona', 'Vicente', 'mariamar.carmona.vicente@email.com', 8, '1991-06-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosario', 'Bravo', 'Reyes', 'mariarosario.bravo.reyes@email.com', 8, '1999-02-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Susana', 'Romero', 'Carrasco', 'susana.romero.carrasco@email.com', 1, '1998-08-24');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Pedro', 'Gallego', 'Blanco', 'pedro.gallego.blanco@email.com', 6, '1993-01-30');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Miguel angel', 'Moreno', 'Fernandez', 'miguelangel.moreno.fernandez@email.com', 13, '2000-02-20');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jaime', 'IbaÑez', 'Caballero', 'jaime.ibaÑez.caballero@email.com', 12, '1995-06-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Claudia', 'Pascual', 'Rodriguez', 'claudia.pascual.rodriguez@email.com', 9, '1997-10-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julia', 'PeÑa', 'Cabrera', 'julia.peÑa.cabrera@email.com', 7, '1996-05-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'David', 'Molina', 'Mendez', 'david.molina.mendez@email.com', 14, '1992-03-31');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julio', 'Pascual', 'Guerrero', 'julio.pascual.guerrero@email.com', 5, '1998-02-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rodrigo', 'Soto', 'Garrido', 'rodrigo.soto.garrido@email.com', 4, '1990-08-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria antonia', 'Ramos', 'Lorenzo', 'mariaantonia.ramos.lorenzo@email.com', 11, '1991-03-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rafael', 'Soler', 'PeÑa', 'rafael.soler.peÑa@email.com', 3, '1992-09-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria dolores', 'Dominguez', 'Vidal', 'mariadolores.dominguez.vidal@email.com', 4, '1998-01-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose angel', 'Campos', 'Vicente', 'joseangel.campos.vicente@email.com', 11, '1994-03-18');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alex', 'Esteban', 'Marquez', 'alex.esteban.marquez@email.com', 13, '1995-10-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria carmen', 'Iglesias', 'Crespo', 'mariacarmen.iglesias.crespo@email.com', 4, '1991-04-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ana', 'Rojas', 'Morales', 'ana.rojas.morales@email.com', 1, '1995-02-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juana', 'Gil', 'Ortega', 'juana.gil.ortega@email.com', 12, '1993-04-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Marta', 'Torres', 'Carrasco', 'marta.torres.carrasco@email.com', 8, '1997-08-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luis', 'Castro', 'Reyes', 'luis.castro.reyes@email.com', 2, '1999-10-30');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Pedro', 'Rojas', 'Cortes', 'pedro.rojas.cortes@email.com', 10, '1996-09-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria josefa', 'Gutierrez', 'Ortiz', 'mariajosefa.gutierrez.ortiz@email.com', 13, '2000-07-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lidia', 'Alvarez', 'PeÑa', 'lidia.alvarez.peÑa@email.com', 8, '1999-08-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Victor manuel', 'Santana', 'Velasco', 'victormanuel.santana.velasco@email.com', 13, '2000-08-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angel', 'Gil', 'Lopez', 'angel.gil.lopez@email.com', 4, '1993-08-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Gloria', 'Roman', 'Gallardo', 'gloria.roman.gallardo@email.com', 9, '1997-03-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Monica', 'Mora', 'Blanco', 'monica.mora.blanco@email.com', 12, '1992-01-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alberto', 'Aguilar', 'Vicente', 'alberto.aguilar.vicente@email.com', 2, '1996-10-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Samuel', 'Perez', 'Marquez', 'samuel.perez.marquez@email.com', 1, '1994-08-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Cristian', 'PeÑa', 'Vazquez', 'cristian.peÑa.vazquez@email.com', 14, '1997-03-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Miriam', 'Lopez', 'Martinez', 'miriam.lopez.martinez@email.com', 1, '1995-09-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Fatima', 'Moya', 'Leon', 'fatima.moya.leon@email.com', 9, '1998-02-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andrea', 'Vidal', 'IbaÑez', 'andrea.vidal.ibaÑez@email.com', 12, '1998-02-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sofia', 'Marquez', 'Flores', 'sofia.marquez.flores@email.com', 10, '1996-07-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosa', 'Serrano', 'Jimenez', 'mariarosa.serrano.jimenez@email.com', 8, '1990-02-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andres', 'Lozano', 'Castro', 'andres.lozano.castro@email.com', 14, '1992-10-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan manuel', 'Dominguez', 'Gil', 'juanmanuel.dominguez.gil@email.com', 3, '1997-06-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andres', 'Ramirez', 'Gallardo', 'andres.ramirez.gallardo@email.com', 11, '1995-12-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Adrian', 'Cabrera', 'Morales', 'adrian.cabrera.morales@email.com', 7, '1996-09-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Francisco', 'Prieto', 'Vargas', 'francisco.prieto.vargas@email.com', 14, '1997-06-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Santiago', 'Ruiz', 'Carrasco', 'santiago.ruiz.carrasco@email.com', 2, '1997-09-20');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joaquin', 'Diez', 'Molina', 'joaquin.diez.molina@email.com', 1, '1997-02-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria luisa', 'Santos', 'PeÑa', 'marialuisa.santos.peÑa@email.com', 7, '1995-09-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'David', 'Rojas', 'Lozano', 'david.rojas.lozano@email.com', 6, '1990-08-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lidia', 'Sanz', 'Romero', 'lidia.sanz.romero@email.com', 6, '1992-12-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Isabel', 'Jimenez', 'Serrano', 'isabel.jimenez.serrano@email.com', 11, '1994-10-24');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alfredo', 'Sanchez', 'Vega', 'alfredo.sanchez.vega@email.com', 9, '1992-08-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose antonio', 'Carrasco', 'Campos', 'joseantonio.carrasco.campos@email.com', 4, '1993-09-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ana belen', 'Alonso', 'Ortega', 'anabelen.alonso.ortega@email.com', 12, '1999-01-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan antonio', 'Ortega', 'Caballero', 'juanantonio.ortega.caballero@email.com', 12, '1993-10-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luisa', 'Hernandez', 'Prieto', 'luisa.hernandez.prieto@email.com', 7, '1996-01-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andrea', 'Velasco', 'Lozano', 'andrea.velasco.lozano@email.com', 14, '1991-01-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ana maria', 'Vicente', 'Bravo', 'anamaria.vicente.bravo@email.com', 6, '1996-02-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Emilio', 'Marquez', 'Vicente', 'emilio.marquez.vicente@email.com', 11, '1994-12-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria elena', 'Torres', 'Crespo', 'mariaelena.torres.crespo@email.com', 1, '1991-07-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ruben', 'Sanz', 'Sanz', 'ruben.sanz.sanz@email.com', 3, '1994-09-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sebastian', 'Alonso', 'Gonzalez', 'sebastian.alonso.gonzalez@email.com', 14, '1996-09-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alba', 'Leon', 'Pastor', 'alba.leon.pastor@email.com', 2, '1999-07-18');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joaquin', 'Diaz', 'Alvarez', 'joaquin.diaz.alvarez@email.com', 8, '1991-11-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Eduardo', 'Torres', 'Carmona', 'eduardo.torres.carmona@email.com', 12, '1994-08-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria pilar', 'Sanz', 'Suarez', 'mariapilar.sanz.suarez@email.com', 6, '1994-01-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Esther', 'Suarez', 'Bravo', 'esther.suarez.bravo@email.com', 13, '1998-01-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Antonia', 'Soler', 'Castro', 'antonia.soler.castro@email.com', 10, '1997-07-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Adrian', 'Pascual', 'Vega', 'adrian.pascual.vega@email.com', 14, '1999-02-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Raquel', 'Cano', 'Perez', 'raquel.cano.perez@email.com', 14, '2000-04-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Daniela', 'Iglesias', 'Rubio', 'daniela.iglesias.rubio@email.com', 10, '2000-06-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andres', 'Morales', 'Lopez', 'andres.morales.lopez@email.com', 13, '1992-02-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan manuel', 'Ramos', 'Guerrero', 'juanmanuel.ramos.guerrero@email.com', 3, '1999-08-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Santiago', 'Leon', 'Diez', 'santiago.leon.diez@email.com', 11, '1991-11-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angeles', 'Serrano', 'Garrido', 'angeles.serrano.garrido@email.com', 12, '1990-04-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria elena', 'Flores', 'Bravo', 'mariaelena.flores.bravo@email.com', 11, '1994-11-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lucas', 'Delgado', 'Saez', 'lucas.delgado.saez@email.com', 9, '1997-03-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ismael', 'Nieto', 'Serrano', 'ismael.nieto.serrano@email.com', 9, '1991-08-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Victor', 'Perez', 'Iglesias', 'victor.perez.iglesias@email.com', 3, '1991-01-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Enrique', 'Santos', 'Reyes', 'enrique.santos.reyes@email.com', 13, '1996-03-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose luis', 'Herrera', 'Hidalgo', 'joseluis.herrera.hidalgo@email.com', 10, '1996-09-02');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angeles', 'Moya', 'Lopez', 'angeles.moya.lopez@email.com', 13, '1999-02-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Francisca', 'Garrido', 'Rubio', 'francisca.garrido.rubio@email.com', 1, '1990-02-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jorge', 'Martin', 'Bravo', 'jorge.martin.bravo@email.com', 4, '1994-12-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ivan', 'Soto', 'Parra', 'ivan.soto.parra@email.com', 8, '1993-09-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Francisca', 'Garcia', 'Rojas', 'francisca.garcia.rojas@email.com', 12, '1996-12-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Eva', 'Aguilar', 'Carmona', 'eva.aguilar.carmona@email.com', 7, '1992-08-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luis miguel', 'Medina', 'Jimenez', 'luismiguel.medina.jimenez@email.com', 3, '1992-05-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Nicolas', 'Fuentes', 'Campos', 'nicolas.fuentes.campos@email.com', 3, '2000-06-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan manuel', 'Soto', 'Gomez', 'juanmanuel.soto.gomez@email.com', 13, '1990-10-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Francisca', 'Torres', 'Romero', 'francisca.torres.romero@email.com', 9, '1991-10-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Cesar', 'Diaz', 'Santos', 'cesar.diaz.santos@email.com', 2, '1998-01-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Pilar', 'Navarro', 'Parra', 'pilar.navarro.parra@email.com', 4, '1996-03-01');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Josefa', 'Pascual', 'Gallego', 'josefa.pascual.gallego@email.com', 2, '1999-08-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Felix', 'Soler', 'Prieto', 'felix.soler.prieto@email.com', 10, '1992-03-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Carmen', 'Mora', 'Lopez', 'carmen.mora.lopez@email.com', 11, '1994-01-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andrea', 'Vidal', 'Moya', 'andrea.vidal.moya@email.com', 2, '1993-05-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Marina', 'Esteban', 'Ortega', 'marina.esteban.ortega@email.com', 14, '1993-03-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria concepcion', 'Diez', 'Martinez', 'mariaconcepcion.diez.martinez@email.com', 11, '1994-12-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'David', 'Carmona', 'Vargas', 'david.carmona.vargas@email.com', 3, '1994-02-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose maria', 'Navarro', 'Santiago', 'josemaria.navarro.santiago@email.com', 7, '1996-05-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alfredo', 'Santana', 'Rojas', 'alfredo.santana.rojas@email.com', 6, '1997-10-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Joaquin', 'Santana', 'Cortes', 'joaquin.santana.cortes@email.com', 3, '1997-12-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Domingo', 'Esteban', 'Alvarez', 'domingo.esteban.alvarez@email.com', 12, '2000-03-31');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Gonzalo', 'Santana', 'Torres', 'gonzalo.santana.torres@email.com', 1, '1992-10-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose manuel', 'Prieto', 'Aguilar', 'josemanuel.prieto.aguilar@email.com', 5, '1994-12-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Manuel', 'Martinez', 'Blanco', 'manuel.martinez.blanco@email.com', 2, '1990-08-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ricardo', 'Saez', 'Aguilar', 'ricardo.saez.aguilar@email.com', 2, '1995-02-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Raul', 'Gimenez', 'Sanz', 'raul.gimenez.sanz@email.com', 7, '1998-09-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosa', 'Duran', 'Saez', 'mariarosa.duran.saez@email.com', 13, '1993-07-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jaime', 'Montero', 'Rojas', 'jaime.montero.rojas@email.com', 8, '1996-03-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Montserrat', 'Molina', 'Pastor', 'montserrat.molina.pastor@email.com', 11, '1997-04-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria jose', 'Marquez', 'Ramirez', 'mariajose.marquez.ramirez@email.com', 5, '1993-11-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Natalia', 'Sanz', 'Herrera', 'natalia.sanz.herrera@email.com', 1, '1993-09-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Encarnacion', 'Alonso', 'Santos', 'encarnacion.alonso.santos@email.com', 9, '1993-04-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Albert', 'Nieto', 'Gutierrez', 'albert.nieto.gutierrez@email.com', 11, '1997-10-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Yolanda', 'Ruiz', 'Santiago', 'yolanda.ruiz.santiago@email.com', 12, '1992-06-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Isabel', 'Ruiz', 'Rojas', 'isabel.ruiz.rojas@email.com', 11, '1995-06-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan manuel', 'Gonzalez', 'Prieto', 'juanmanuel.gonzalez.prieto@email.com', 3, '1996-06-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Nerea', 'Crespo', 'Crespo', 'nerea.crespo.crespo@email.com', 1, '1993-07-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Yolanda', 'Pastor', 'Vega', 'yolanda.pastor.vega@email.com', 5, '1992-04-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Raul', 'Herrera', 'Gil', 'raul.herrera.gil@email.com', 14, '1991-12-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rosa', 'Diaz', 'Alvarez', 'rosa.diaz.alvarez@email.com', 11, '1999-04-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan jose', 'Pascual', 'Pastor', 'juanjose.pascual.pastor@email.com', 2, '1995-08-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'David', 'Arias', 'Vidal', 'david.arias.vidal@email.com', 4, '1998-11-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lucas', 'Marquez', 'Rodriguez', 'lucas.marquez.rodriguez@email.com', 5, '1992-02-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Lidia', 'Molina', 'Vega', 'lidia.molina.vega@email.com', 8, '1994-06-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Raquel', 'Sanz', 'Soto', 'raquel.sanz.soto@email.com', 10, '1994-11-18');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Eduardo', 'IbaÑez', 'Vazquez', 'eduardo.ibaÑez.vazquez@email.com', 5, '1996-11-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Domingo', 'Torres', 'Ferrer', 'domingo.torres.ferrer@email.com', 13, '1996-04-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Xavier', 'Nieto', 'Blanco', 'xavier.nieto.blanco@email.com', 14, '1999-04-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Amparo', 'Rodriguez', 'Gallego', 'amparo.rodriguez.gallego@email.com', 9, '1992-04-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Iker', 'Rubio', 'Santiago', 'iker.rubio.santiago@email.com', 12, '1994-07-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Martin', 'Prieto', 'Marquez', 'martin.prieto.marquez@email.com', 10, '1990-01-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luis', 'Herrera', 'Mora', 'luis.herrera.mora@email.com', 5, '1995-05-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Adrian', 'Suarez', 'Ortiz', 'adrian.suarez.ortiz@email.com', 12, '1997-01-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Manuela', 'Guerrero', 'Carmona', 'manuela.guerrero.carmona@email.com', 2, '1999-09-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan manuel', 'Ortega', 'Reyes', 'juanmanuel.ortega.reyes@email.com', 13, '1994-05-06');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Rosa maria', 'Ortega', 'Duran', 'rosamaria.ortega.duran@email.com', 1, '1995-02-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Aurora', 'Ferrer', 'Guerrero', 'aurora.ferrer.guerrero@email.com', 2, '1998-08-24');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sergio', 'Serrano', 'Vargas', 'sergio.serrano.vargas@email.com', 2, '1992-02-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria jesus', 'Rubio', 'Blanco', 'mariajesus.rubio.blanco@email.com', 4, '1996-11-20');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ines', 'Moreno', 'Gil', 'ines.moreno.gil@email.com', 3, '1993-07-20');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria rosa', 'Dominguez', 'Roman', 'mariarosa.dominguez.roman@email.com', 3, '1999-09-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Manuela', 'Duran', 'Cruz', 'manuela.duran.cruz@email.com', 9, '1992-11-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose', 'Martinez', 'Sanz', 'jose.martinez.sanz@email.com', 6, '1990-09-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mohamed', 'Crespo', 'Cortes', 'mohamed.crespo.cortes@email.com', 9, '1992-12-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angela', 'Gomez', 'Hidalgo', 'angela.gomez.hidalgo@email.com', 8, '2000-05-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Guillermo', 'Vega', 'Rodriguez', 'guillermo.vega.rodriguez@email.com', 2, '1993-08-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Salvador', 'Gonzalez', 'Esteban', 'salvador.gonzalez.esteban@email.com', 8, '1996-01-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Francisco jose', 'Rojas', 'Rodriguez', 'franciscojose.rojas.rodriguez@email.com', 12, '1992-10-16');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andrea', 'Castillo', 'Vargas', 'andrea.castillo.vargas@email.com', 4, '1998-07-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Miguel angel', 'Saez', 'Garcia', 'miguelangel.saez.garcia@email.com', 11, '1993-06-02');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Fatima', 'Molina', 'Santos', 'fatima.molina.santos@email.com', 14, '1993-01-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Salvador', 'Mora', 'Velasco', 'salvador.mora.velasco@email.com', 8, '1993-03-02');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mariano', 'Navarro', 'Cortes', 'mariano.navarro.cortes@email.com', 6, '1990-12-11');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria pilar', 'Roman', 'Marquez', 'mariapilar.roman.marquez@email.com', 4, '1994-07-12');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Josep', 'NuÑez', 'Rodriguez', 'josep.nuÑez.rodriguez@email.com', 5, '1995-12-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Beatriz', 'Prieto', 'Suarez', 'beatriz.prieto.suarez@email.com', 11, '1994-09-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jorge', 'Caballero', 'Garrido', 'jorge.caballero.garrido@email.com', 7, '1999-05-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alba', 'Suarez', 'Carmona', 'alba.suarez.carmona@email.com', 6, '1994-06-04');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angela', 'Romero', 'Gil', 'angela.romero.gil@email.com', 6, '2000-12-27');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose maria', 'Aguilar', 'Crespo', 'josemaria.aguilar.crespo@email.com', 12, '1999-10-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Natalia', 'Ortiz', 'Sanchez', 'natalia.ortiz.sanchez@email.com', 5, '1999-02-14');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sandra', 'Esteban', 'Castillo', 'sandra.esteban.castillo@email.com', 4, '1998-01-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria carmen', 'Soler', 'Saez', 'mariacarmen.soler.saez@email.com', 13, '1992-09-08');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Yolanda', 'Aguilar', 'Rojas', 'yolanda.aguilar.rojas@email.com', 5, '1991-05-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Gloria', 'Gallego', 'Duran', 'gloria.gallego.duran@email.com', 5, '1998-10-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Fatima', 'Vega', 'Calvo', 'fatima.vega.calvo@email.com', 12, '1993-07-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Cesar', 'Sanz', 'Garcia', 'cesar.sanz.garcia@email.com', 4, '1993-09-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Eduardo', 'Ferrer', 'Soto', 'eduardo.ferrer.soto@email.com', 4, '1996-10-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Inmaculada', 'Castillo', 'Moya', 'inmaculada.castillo.moya@email.com', 12, '1997-01-07');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Diego', 'Fuentes', 'Alvarez', 'diego.fuentes.alvarez@email.com', 9, '1998-07-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Veronica', 'Santos', 'Vargas', 'veronica.santos.vargas@email.com', 9, '1993-04-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Felix', 'Martin', 'Delgado', 'felix.martin.delgado@email.com', 13, '1993-07-02');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alvaro', 'Benitez', 'Alonso', 'alvaro.benitez.alonso@email.com', 11, '1997-01-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Xavier', 'Alvarez', 'Hidalgo', 'xavier.alvarez.hidalgo@email.com', 6, '1996-02-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jose luis', 'Bravo', 'Perez', 'joseluis.bravo.perez@email.com', 1, '1999-05-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Luis', 'Gimenez', 'Reyes', 'luis.gimenez.reyes@email.com', 3, '1997-04-03');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Josefa', 'Soler', 'Rodriguez', 'josefa.soler.rodriguez@email.com', 3, '2000-02-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julian', 'Leon', 'Campos', 'julian.leon.campos@email.com', 6, '1997-07-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria angeles', 'Ortega', 'Romero', 'mariaangeles.ortega.romero@email.com', 9, '1997-08-26');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Sofia', 'Vidal', 'Sanchez', 'sofia.vidal.sanchez@email.com', 7, '1993-12-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Julian', 'Benitez', 'Mendez', 'julian.benitez.mendez@email.com', 6, '1999-10-10');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angeles', 'Mendez', 'Molina', 'angeles.mendez.molina@email.com', 2, '1991-03-19');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Ana belen', 'Fuentes', 'Saez', 'anabelen.fuentes.saez@email.com', 3, '1999-02-13');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Inmaculada', 'Ramos', 'Lozano', 'inmaculada.ramos.lozano@email.com', 8, '1997-03-21');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Natalia', 'Serrano', 'Cortes', 'natalia.serrano.cortes@email.com', 5, '1999-03-22');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria josefa', 'Gallardo', 'Rojas', 'mariajosefa.gallardo.rojas@email.com', 11, '1995-07-28');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria concepcion', 'Garcia', 'Caballero', 'mariaconcepcion.garcia.caballero@email.com', 4, '1997-02-15');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alfredo', 'Diaz', 'Moya', 'alfredo.diaz.moya@email.com', 4, '1998-04-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Juan', 'Gallego', 'Ferrer', 'juan.gallego.ferrer@email.com', 13, '2000-10-18');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Andrea', 'Santiago', 'Vicente', 'andrea.santiago.vicente@email.com', 6, '1995-03-29');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Alejandro', 'Castro', 'Gimenez', 'alejandro.castro.gimenez@email.com', 11, '1995-08-31');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Celia', 'Vazquez', 'Ruiz', 'celia.vazquez.ruiz@email.com', 2, '1992-12-09');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Angela', 'Gallego', 'Vicente', 'angela.gallego.vicente@email.com', 14, '1990-12-17');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria mar', 'MuÑoz', 'Diez', 'mariamar.muÑoz.diez@email.com', 10, '1997-05-25');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Mario', 'Gallardo', 'Castro', 'mario.gallardo.castro@email.com', 3, '1997-10-05');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Maria victoria', 'NuÑez', 'Gallardo', 'mariavictoria.nuÑez.gallardo@email.com', 7, '1999-10-23');
insert into ALUMNO (id, nombre, apellido1, apellido2, email, curso_id, fecha_nacimiento) values (NEXTVAL('alumno_seq'), 'Jesus', 'Moreno', 'Cruz', 'jesus.moreno.cruz@email.com', 4, '1994-11-16');
